
#ifndef ZygiskImGui_HOOK_H
#define ZygiskImGui_HOOK_H

#include <jni.h>

static int enable_hack;
static char *game_data_dir = NULL;

int isGame(JNIEnv *env, jstring appDataDir);

void *hack_thread(void *arg);

#include <android/log.h>

enum RPCList
{
    ActivateMechRPC,
    AddBonusAfterKillPlayerRPC,
    AddForceRPC,
    AddFreezerRayWithLength,
    AddPaticleBazeRPC,
    AddPlayerInCapturePoint,
    AddScoreDuckHuntRPC,
    AddWeaponAfterKillPlayerRPC,
    AdvancedEffectRPC,
    AdvancedEffectWithSenderRPC,
    ApplyDamageRPC,
    ApplyDebuffRPC,
    ChargeGunAnimation,
    ClearScoreCommandInFlagGameRPC,
    Collide,
    CountKillsCommandSynch,
    CreateChestRPC,
    DeactivateMechRPC,
    DestroyRpc,
    GetInPlayerRPC,
    ShowSelectedFortNotification,
    fireFlash,
    GetBonusRewardRPC,
    ActivateGadgetRPC,
    GetDamageRPC,
    RespawnRPC,
    Go,
    GoBazaRPC,
    GoMatchRPC,
    HoleRPC,
    ImDeadInHungerGamesRPC,
    imDeath,
    ImKilledRPC,
    IsVisible_RPC,
    KilledByRPC,
    LikeRPC,
    MakeBonusRPC,
    MeKillRPC,
    OpponentLeftGame,
    PlayDestroyEffectRpc,
    PlayerEffectRPC,
    PlayMusic,
    PlayPortalSoundRPC,
    PlayZombieAttackRPC,
    PlayZombieRunRPC,
    plusCountKillsCommand,
    CheckActivityRPC,
    HitByVehicleRPC,
    ReloadGun,
    RemoveBonusRPC,
    RemoveBonusWithRewardRPC,
    RemovePlayerInCapturePoint,
    ResumeMatchRPC,
    RevengeRequestRPC,
    SendBuffParameters,
    SendChatMessageWithIcon,
    SendSystemMessegeFromFlagAddScoreRPC,
    SendSystemMessegeFromFlagDroppedRPC,
    SendSystemMessegeFromFlagReturnedRPC,
    SetArmorVisInvisibleRPC,
    setBootsRPC,
    SetBotHealthRPC,
    setCapeRPC,
    SetCaptureRPC,
    SetEnemyArmor,
    SetEnemyBoots,
    SetEnemyCape,
    SetEnemyHat,
    SetEnemyMask,
    SetEnemyPet,
    SetEnemySkin,
    SetEnemyWeapon,
    SetGadgetEffectActiveRPC,
    SetGadgetesRPC,
    SetHatWithInvisebleRPC,
    SetBigHeadRPC,
    SetJetpackEnabledRPC,
    SetJetpackParticleEnabledRPC,
    SetMaskRPC,
    SetMyClanTexture,
    SetMySkin,
    SetNickName,
    SetNOCaptureRPC,
    SetPixelBookID,
    SetRocketActive,
    SetRocketActiveWithCharge,
    SetRocketStickedRPC,
    SetTargetRPC,
    SetVisibleFireEffectRpc,
    SetWeaponRPC,
    SetWeaponSkinRPC,
    SetWearIsInvisibleRPC,
    ShotRPC,
    ShowBonuseParticleRPC,
    ShowExplosion,
    ShowMultyKillRPC,
    SinchCapture,
    SlowdownRPC,
    StartFlashRPC,
    StartGame,
    StartMatchRPC,
    StartNewRespanObjectRpc,
    StartRocketRPC,
    StartShootLoopRPC,
    StartTurretRPC,
    SynchCaptureCounter,
    SynchCaptureCounterNewPlayer,
    SynchGameRating,
    SynchGameTimer,
    SynchNamberSpawnZoneRPC,
    SynchNumUpdateRPC,
    SynchronizeTimeRPC,
    SynchScoreCommandRPC,
    SynchScoresCommandsNewPlayerRPC,
    SynchScoresCommandsRPC,
    SynchStartTimer,
    SynhCommandRPC,
    SynhCountKillsRPC,
    SynhDeltaHealthRPC,
    SynhHealthRPC,
    SynhIsZoming,
    SynhNameRPC,
    SynhRanksRPC,
    SynhScoreRPC,
    SynhDeltaArmorRPC,
    PropertyRPC,
    winInHungerRPC,
    SetPlayerUniqID,
    SynchLivesItems,
    RegisterPlayerRPC,
    SetGamemodeRPC,
    SetMapRPC,
    StartGameRPC,
    SetReadyRPC,
    QuitFromSquadRPC,
    ShowStartGameRPC,
    StartTimerRPC,
    KickPlayerRPC,
    SynchCurrentCategory,
    ResetVersusTimerRPC,
    StartAirDropItemRPC,
    MakeBetRPC,
    GoTeamMatchRPC,
    StartTeamMatchRPC,
    SynchronizeMatchTimeRPC,
    SetRocketActiveWithNumSmoke,
    SynhDeathCountRPC,
    GoRevengeMatchRPC,
    EndRoundRPC,
    SynchronizeGoTimeRPC,
    SyncronizeTeamWins,
    FireFlashDamagebleRPC,
    SetMaxArmorAndHealthRPC,
    SendEmojiRPC,
    SynchGetGadgets,
    SyncTramPosition,
    UnregisterPlayerRPC,
    SyncLastMoveTime,
    RemoveTargetRPC,
    AttackGateRPC,
    ShotArtilleryRPC,
    SetDestinationRPC,
    SetEquipRPC,
    ShowEndEventRPC,
    ShowEndEventNotificationRPC,
    PlayingInSquadRPC,
    SynchCombatLevelRPC,
    SendPetIdRPC,
    SynchGameLeague,
    ActiveChunkChangedRPC,
    GetBonusRPC,
    SetGliderRPC,
    AddWeaponAfterBonusPreviewRPC,
    RemoveWeaponPreviewRPC,
    SetRoyaleAvatarRPC,
    SetMapPositionSquadRPC,
    PlayerInjuredRPC,
    SynhHealthInjuredRPC,
    PlayerInjuryHealedRPC,
    SetLandingTrailRPC,
    SetUserMapMarkerRPC,
    RemoveUserMapMarkerRPC,
    FlyOnGliderSynchRPC,
    BattleRoyaleSquadMemberKilledRPC,
    HealingByPlayerRPC,
    PlayerInjuryHealingProgressRPC,
    WinRequestRPC,
    SetMyAvatar,
    SetEnemyAvatar,
    SetEquipTypeRPC,
    SynchMinigunRotationRPC,
    PlayZombieBeforeAttackRPC,
    SendNewEmojiRPC,
    SynchVehicleParamsRPC,
    SendBattleEmojiRPC,
    SynchVehicleColorRPC,
    SendChangeMobRPC,
    EnterInTrigger,
    SynchWeaponModulesRPC,
    SynchArmorModulesRPC,
    SetModuleGadgetEffectActiveRPC,
    CreateRocketRPC,
    ShowEffectOnOtherPlayersRPC,
    SetParticleToWeaponRPC,
    RegenerateHealthMob,
    SendKillMob,
    SynhDeltaHealthFromWeaponRPC,
    JumpDisableRPC,
    SetPortalRPC,
    ActivatePolymorphRPC,
    DeactivatePolymorphRPC,
    AlternativeMobAttack,
    AlternativeMobShot,
    DetonateKamikadze,
    SetWeaponLevel,
    MarkEnemy,
    GetDamageToShieldRPC,
    SendOnGroundEffect,
    PluginRPC,
    EnableTeleportEffectsRPC,
    AddAmmoFromWeaponRPC,
    KillerInvisiblityRPC,
    SyncGadgetReflectorCoeffRPC,
    SynchVipStatusRPC,
    InviteToSquadRPC,
    JoinSquadRPC,
    InviteToSquadFailRPC,
    SyncBreakableObjects,
    FreeFallSynchRPC,
    SyncCableCarRPC,
    StartPlantingBomb,
    ResetPlantingBomb,
    StartDefusingBomb,
    ResetDefusingBomb,
    SetIsPaidTransport,
    SyncOwnerTransport,
    SyncCharIdRPC,
    SyncTeammateRegenByMe
};


enum PhotonTargets
{
    All,
    Others,
    MasterClient,
    AllBuffered,
    OthersBuffered,
    AllViaServer,
    AllBufferedViaServer,
    SeflViaServer
};


#define LOG_TAG "ZygiskPG"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

#define HOOKAF(ret, func, ...) \
    ret (*orig##func)(__VA_ARGS__); \
    ret my##func(__VA_ARGS__)


#endif //ZygiskImGui_HOOK_H